apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/mustafadincerr/app-of-apps.git
    targetRevision: HEAD
    path: app-of-apps
  syncPolicy:
    automated:
      prune: false 
      selfHeal: true
